# Use an official Python image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy all files from your project folder to the container's /app folder
COPY . /app

# Install the Flask dependency inside the container
RUN pip install -r requirements.txt

# Command to run the Flask app
CMD ["python", "app.py"]
